version: 2
jobs:
  build:
    working_directory: ~/setup-circleci
    docker:
      - image: circleci/node:10.6-jessie
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm deps
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: lint
          command: npm run lint
      - run:
          name: unit
          command: npm run test:unit

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
