version: 2

defaults: &defaults
  working_directory: ~/repo/circle-ci-test
  docker:
    #- image: node:8
    - image: cypress/base:8
restore_node_modules: &restore_node_modules
  restore_cache:
    name: Restore node_modules cache
    keys:
      - v1-dependencies-{{ checksum "package.json" }}
      - v1-dependencies-

jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - *restore_node_modules
      - run:
          name: yarn --version
          command: yarn --version
      - run:
          name: yarn install
          command: yarn install
      - run:
          command: ls -l
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - ~/repo/.cache
      - persist_to_workspace:
          root: ~/repo
          paths:
            - circle-ci-test/

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - *restore_node_modules
      - run:
          name: lint
          command: npm run lint

  unit:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - *restore_node_modules
      - run:
          name: unit
          command: npm run test:unit

  e2e:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - *restore_node_modules
      - run:
          name: e2e
          command: npm run test:e2e:headless

workflows:
  version: 2
  build_and_test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - unit:
          requires:
            - install
      - e2e:
          requires:
            - install
