# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/setup-circleci
    docker:
      - image: circleci/node:10.6-jessie
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install npm deps
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test_lint:
    working_directory: ~/setup-circleci
    docker: circleci/node:10.6-jessie
    steps:
      - run:
          name: lint
          command: npm run lint
  test_unit:
    working_directory: ~/setup-circleci
    docker: circleci/node:10.6-jessie
    steps:
      - run:
          name: unit
          command: npm run test:unit
  test_e2e:
    working_directory: ~/setup-circleci
    docker: cypress/base
    steps:
      - run:
          name: e2e
          command: npm run test:e2e:headless
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_lint:
          requires:
            - build
      - test_unit:
          requires:
            - build
      - test_e2e:
          requires:
            - build
